apiVersion: v1
kind: Service
metadata:
  name: db-influxdb
  labels:
    app: influxdb
spec:
  ports:
    - port: 8086
  selector:
    app: influxdb
    tier: influxdb
  type: ClusterIP
  clusterIP: 10.99.99.69
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: db-influxdb
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
        tier: influxdb
    spec:
      containers:
      - imagePullPolicy: Never
        image: d_influxdb
        name: influxdb
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
        - name: docker-storage
          mountPath: /var/run/docker.sock
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      - name: docker-storage
        hostPath:
          path: /var/run/docker.sock