apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    -  port: 5000
       targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - imagePullPolicy: Never
        image: d_phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
        livenessProbe:
          exec:
            command:
            - sh
            - health.sh
          initialDelaySeconds: 5
          periodSeconds: 2