apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    -  port: 5050
       targetPort: 5050
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - imagePullPolicy: Never
        image: d_wordpress
        name: wordpress
        ports:
        - containerPort: 5050
          name: wordpress
        livenessProbe:
          exec:
            command:
            - cat
            - /wordpress/index.php
          initialDelaySeconds: 5
          periodSeconds: 1
